const lessonData = {};

lessonData["01_AlCapone.mp3"] = [{
    text: "1. Al Capone. Al Capone was the most famous gangster in American history. During the 1920s, the United States made alcohol illegal. This was called 'Prohibition.' Al Capone became very rich and powerful by selling illegal alcohol in Chicago. He was a very violent man who used a large gang to control the city. He was often called 'Scarface' because of a mark on his cheek. Although everyone knew he was a criminal, the police could not catch him for a long time because he was very clever and paid off many officials. He was responsible for many deaths, including the famous St. Valentine's Day Massacre. Finally, the government used a different way to stop him. They found out he was not paying his taxes. In 1931, he was sent to prison for tax evasion. He spent several years in the famous Alcatraz prison. He died in 1947. He remains a symbol of the 'classic' American gangster from the old movie era.",
    dict: { "illegal": "yasadışı", "prohibition": "içki yasağı", "powerful": "güçlü", "violent": "şiddet eğilimli", "scarface": "yaralı yüz", "cheek": "yanak", "criminal": "suçlu", "clever": "zeki", "officials": "yetkililer", "responsible": "sorumlu", "massacre": "katliam", "government": "hükümet", "taxes": "vergiler", "prison": "hapishane", "evasion": "kaçakçılık/kaçınma" },
    questions: [ {q:"Was Al Capone a famous gangster?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he sell illegal alcohol?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a very gentle man?", a_en:"No", a_tr:"Hayır"}, {q:"Did the police catch him easily?", a_en:"No", a_tr:"Hayır"}, {q:"Was he sent to prison for tax evasion?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he spend time in Alcatraz?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he die in 1947?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["02_ArnoldRothstein.mp3"] = [{
    text: "2. Arnold Rothstein. Arnold Rothstein was a very intelligent and quiet criminal in New York. He was known as 'The Brain' because he treated crime like a big business. He was a professional gambler and a kingpin of the Jewish-American mob. Rothstein is most famous for allegedly fixing the 1919 World Series baseball games. He paid players to lose so he could win a lot of money on bets. He was a mentor to many other famous gangsters like Lucky Luciano and Meyer Lansky. He taught them how to be organized and how to deal with politicians. Rothstein was rarely seen with a gun; he used his mind and his money to get power. In 1928, he was shot in a hotel because he refused to pay a large gambling debt. He died without telling the police who shot him. He is remembered as the man who turned simple street gangs into a massive, organized criminal industry.",
    dict: { "intelligent": "zeki", "quiet": "sessiz", "gambler": "kumarbaz", "kingpin": "elebaşı", "allegedly": "iddia edildiğine göre", "fixing": "hile karıştırma", "bets": "bahisler", "mentor": "akıl hocası", "organized": "organize", "politicians": "politikacılar", "rarely": "nadiren", "refused": "reddetti", "debt": "borç", "industry": "endüstri/sanayi" },
    questions: [ {q:"Was Arnold Rothstein known as The Brain?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he treat crime like a big business?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he famous for fixing baseball games?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he carry a gun all the time?", a_en:"No", a_tr:"Hayır"}, {q:"Was he a mentor to Lucky Luciano?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he tell the police who shot him?", a_en:"No", a_tr:"Hayır"}, {q:"Did he turn street gangs into an industry?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["03_BugsySiegel.mp3"] = [{
    text: "3. Benjamin Bugsy Siegel. Benjamin Siegel was a handsome but very dangerous mobster. People called him 'Bugsy' because he had a very quick and 'crazy' temper, though he hated that name. He was one of the founders of the 'Murder, Inc.' group, which carried out killings for the Mafia. Siegel is most famous for his role in building Las Vegas. In the 1940s, he went to the Nevada desert and used Mafia money to build a massive, luxury hotel and casino called the 'Flamingo.' He dreamed of making Las Vegas a place where people could gamble and have fun in luxury. However, the hotel cost much more money than he expected. The Mafia bosses became angry because they thought he was stealing their money. In 1947, Siegel was shot and killed in his home in California. Just after his death, Las Vegas became a huge success. Today, he is remembered as the man who created the modern Las Vegas.",
    dict: { "handsome": "yakışıklı", "dangerous": "tehlikeli", "temper": "sinir/öfke", "founders": "kurucular", "role": "rol", "desert": "çöl", "luxury": "lüks", "casino": "kumarhane", "dreamed": "hayal etti", "gamble": "kumar oynamak", "expected": "beklenenden", "stealing": "çalmak", "success": "başarı" },
    questions: [ {q:"Did people call Benjamin Siegel Bugsy?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he love the name Bugsy?", a_en:"No", a_tr:"Hayır"}, {q:"Did he build a casino in Las Vegas?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the hotel cost less money than expected?", a_en:"No", a_tr:"Hayır"}, {q:"Did the Mafia bosses think he was stealing?", a_en:"Yes", a_tr:"Evet"}, {q:"Was Siegel shot in his home?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Las Vegas become a success after his death?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["04_BumpyJohnson.mp3"] = [{
    text: "4. Bumpy Johnson. Ellsworth 'Bumpy' Johnson was the legendary 'Godfather of Harlem.' He was a very intelligent man who loved books and chess, but he was also a fierce warrior. He controlled the illegal gambling and rackets in Harlem for decades. In the 1930s, the powerful Italian Mafia, led by Dutch Schultz, tried to take over Harlem. Bumpy Johnson refused to surrender. He led a long and violent street war to keep his neighborhood independent. Eventually, the Italian bosses respected him and made a deal to work with him instead of fighting. Bumpy was very popular in Harlem because he helped the poor and protected his community. He was also a mentor to Frank Lucas. He spent several years in prison but returned to Harlem to rule again. He died of a heart attack in 1968 while eating in a restaurant. His life has been the subject of many movies and television shows because he was a kingpin who stood up to the strongest Mafia families.",
    dict: { "legendary": "efsanevi", "fierce": "şiddetli/korkunç", "warrior": "savaşçı", "rackets": "haraç/yasadışı işler", "decades": "on yıllar", "surrender": "teslim olmak", "independent": "bağımsız", "eventually": "sonunda", "respected": "saygı duydu", "popular": "popüler", "protected": "korudu", "mentor": "akıl hocası", "heart attack": "kalp krizi" },
    questions: [ {q:"Was Bumpy Johnson the Godfather of Harlem?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he love books and chess?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he surrender to the Italian Mafia?", a_en:"No", a_tr:"Hayır"}, {q:"Did he fight a long street war?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he help the poor in his community?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a mentor to Frank Lucas?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he die in a prison cell?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["05_LuckyLuciano.mp3"] = [{
    text: "5. Charles Lucky Luciano. Charles Luciano is often called the father of modern organized crime. He was born in Sicily and moved to New York as a child. He was called 'Lucky' because he survived a brutal attack by a rival gang. Before Luciano, the Mafia was divided into many small groups that were always fighting. Luciano changed everything. In 1931, he created 'The Commission.' This was a group of bosses who met like a board of directors to make rules and stop the violence. He turned the Mafia into a massive, organized business. In 1936, he was sent to prison, but during World War II, the US government asked him for help to protect the New York docks and to help with the invasion of Sicily. Because of his help, he was released from prison but forced to leave the United States. He lived the rest of his life in Italy, where he continued to run his criminal empire from far away until he died in 1962.",
    dict: { "father": "baba", "survived": "hayatta kaldı", "brutal": "acımasız", "rival": "rakip", "divided": "bölünmüş", "created": "yarattı", "board of directors": "yönetim kurulu", "violence": "şiddet", "docks": "rıhtımlar", "invasion": "işgal", "released": "serbest bırakıldı", "forced": "zorlandı", "empire": "imparatorluk" },
    questions: [ {q:"Was Lucky Luciano the father of modern organized crime?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he survive a brutal attack?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he create The Commission?", a_en:"Yes", a_tr:"Evet"}, {q:"Was The Commission like a board of directors?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he help the US government during World War II?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he allowed to stay in the United States?", a_en:"No", a_tr:"Hayır"}, {q:"Did he run his empire from Italy?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["06_CurtisWarren.mp3"] = [{
    text: "6. Curtis Cocky Warren. Curtis Warren is one of the most successful international drug traffickers in British history. He was born in Liverpool and started as a small-time criminal. However, he was very intelligent and quickly built a massive network to move drugs from South America to Europe. He was so successful that he once appeared on the 'Sunday Times Rich List' of the wealthiest people in Britain. The police called him 'Cocky' because he was very bold and often escaped their traps. He used many different ways to hide his business and moved his operations to the Netherlands to avoid the British police. Finally, in 1996, the Dutch police arrested him after they found a massive amount of illegal goods in a warehouse. He has spent many years in different prisons. His story is a famous example of how an individual can build a global criminal empire using modern business methods and international connections.",
    dict: { "traffickers": "kaçakçılar", "intelligent": "zeki", "network": "ağ/şebeke", "wealthiest": "en zengin", "bold": "cesur", "escaped": "kaçtı", "traps": "tuzaklar", "operations": "operasyonlar", "arrested": "tutuklandı", "warehouse": "depo", "individual": "birey", "global": "küresel" },
    questions: [ {q:"Was Curtis Warren a drug trafficker?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he build a massive network?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he on the Sunday Times Rich List?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the police call him Cocky?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he move his operations to the Netherlands?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the police find illegal goods in a warehouse?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he escape prison forever?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["07_DawoodIbrahim.mp3"] = [{
    text: "7. Dawood Ibrahim. Dawood Ibrahim is the most wanted man in India and one of the most powerful crime bosses in the world. He is the leader of a massive organization called 'D-Company.' He started as a small criminal in Mumbai, but he quickly became the boss of the city's underworld. His group is involved in many crimes, including gold smuggling, drug trafficking, and money laundering. He is also accused of being involved in terrorism, specifically the 1993 Mumbai bombings. Because of this, he is considered a global terrorist by many countries. Dawood is a very mysterious figure who is believed to be living in hiding in Pakistan, though the government there denies it. His influence is so large that he has connections to many industries, including the Bollywood film industry. He has managed to avoid the police for more than 30 years and continues to run his criminal empire from a secret location.",
    dict: { "wanted": "aranan", "underworld": "yeraltı dünyası", "smuggling": "kaçakçılık", "trafficking": "ticaret/kaçakçılık", "laundering": "aklama", "accused": "suçlanan", "terrorism": "terörizm", "mysterious": "gizemli", "hiding": "saklanıyor", "denies": "inkar ediyor", "influence": "etki", "connections": "bağlantılar", "avoid": "kaçınmak" },
    questions: [ {q:"Is Dawood Ibrahim the most wanted man in India?", a_en:"Yes", a_tr:"Evet"}, {q:"Is he the leader of D-Company?", a_en:"Yes", a_tr:"Evet"}, {q:"Is his group involved in gold smuggling?", a_en:"Yes", a_tr:"Evet"}, {q:"Is he considered a global terrorist?", a_en:"Yes", a_tr:"Evet"}, {q:"Does the Pakistan government admit he lives there?", a_en:"No", a_tr:"Hayır"}, {q:"Does he have connections to the Bollywood film industry?", a_en:"Yes", a_tr:"Evet"}, {q:"Has he managed to avoid the police for 30 years?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["08_DutchSchultz.mp3"] = [{
    text: "8. Dutch Schultz. Dutch Schultz was a ruthless and very greedy Jewish-American mobster in New York. His real name was Arthur Flegenheimer. He made a massive fortune selling illegal alcohol during Prohibition and running illegal numbers games in Harlem. He was known for having a very bad temper and being very violent with his enemies and even his own men. In the 1930s, the government started a major investigation into his business. Schultz wanted to kill the special prosecutor, Thomas Dewey, to stop the investigation. The other Mafia bosses in 'The Commission' were afraid that killing a government official would bring too much heat on everyone. They told Schultz 'no,' but he decided to do it anyway. To protect themselves, the other bosses ordered a hit on Schultz. In 1935, he was shot in a restaurant in New Jersey. He lived for several hours in the hospital, saying many strange things before he died. He is remembered as a boss who was too wild even for the Mafia.",
    dict: { "ruthless": "acımasız", "greedy": "açgözlü", "fortune": "servet", "temper": "sinir/öfke", "investigation": "soruşturma", "prosecutor": "savcı", "afraid": "korkmuş", "ordered": "emretti", "hit": "suikast/vurma", "hospital": "hastane", "strange": "tuhaf", "wild": "vahşi" },
    questions: [ {q:"Was Dutch Schultz a ruthless mobster?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he make a massive fortune selling illegal alcohol?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he have a very bad temper?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he want to kill the special prosecutor?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the other Mafia bosses say yes to his plan?", a_en:"No", a_tr:"Hayır"}, {q:"Did the other bosses order a hit on Schultz?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he die instantly in the restaurant?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["09_FrankLucas.mp3"] = [{
    text: "9. Frank Lucas. Frank Lucas was a very powerful drug lord in Harlem during the 1960s and 70s. He was a student of Bumpy Johnson. Lucas became famous for changing the way drugs were brought into the United States. He did not want to pay the Italian Mafia for his supplies, so he traveled to Southeast Asia during the Vietnam War. He made a deal to buy high-purity heroin directly from the source. He became very rich by smuggling the heroin inside the coffins of dead American soldiers returning from the war. This was called the 'Cadaver Connection.' He sold his product under the name 'Blue Magic.' Because he cut out the middleman, his heroin was better and cheaper than anyone else's. He lived a very luxury life and was a famous figure in Harlem. He was finally arrested in 1975 by a dedicated police detective. His story was later made into the famous movie American Gangster.",
    dict: { "powerful": "güçlü", "drug lord": "uyuşturucu baronu", "supplies": "tedarik/malzemeler", "source": "kaynak", "smuggling": "kaçakçılık", "coffins": "tabutlar", "dead": "ölü", "soldiers": "askerler", "middleman": "aracı", "purity": "saflık", "cheaper": "daha ucuz", "luxury": "lüks", "dedicated": "kendini adamış" },
    questions: [ {q:"Was Frank Lucas a student of Bumpy Johnson?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he buy heroin directly from the source?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he smuggle drugs inside the coffins of soldiers?", a_en:"Yes", a_tr:"Evet"}, {q:"Was his product called Red Magic?", a_en:"No", a_tr:"Hayır"}, {q:"Was his heroin better and cheaper?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he live a luxury life?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he arrested by a dedicated police detective?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["10_GriseldaBlanco.mp3"] = [{
    text: "10. Griselda Blanco. Griselda Blanco was one of the most feared and violent women in criminal history. She was known as the 'Cocaine Godmother' or the 'Black Widow.' She was a leader of the Medellín Cartel in Colombia and moved to Miami in the 1970s. She was a pioneer of the cocaine trade and was responsible for flooding the streets of Miami with drugs. Griselda was famous for her extreme violence; she created the 'motorcycle assassin' technique, where killers on bikes would shoot people and drive away quickly. She was involved in a bloody war in Miami called the 'Cocaine Cowboy Wars.' It is said she was responsible for hundreds of murders. She was very wealthy and even named one of her sons 'Michael Corleone' after the character in The Godfather. She spent many years in prison in the US before being sent back to Colombia. In 2012, she was killed in a motorcycle shooting, the same way she used to kill her enemies.",
    dict: { "feared": "korkulan", "pioneer": "öncü", "flooding": "sel gibi doldurma", "extreme": "aşırı", "assassin": "suikastçi", "technique": "teknik", "bloody": "kanlı", "wealthy": "zengin", "named": "isim verdi", "character": "karakter", "shooting": "silahlı saldırı" },
    questions: [ {q:"Was Griselda Blanco called the Cocaine Godmother?", a_en:"Yes", a_tr:"Evet"}, {q:"Was she a pioneer of the cocaine trade?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she create the motorcycle assassin technique?", a_en:"Yes", a_tr:"Evet"}, {q:"Was she involved in the Cocaine Cowboy Wars?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she name her son Michael Corleone?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she spend many years in prison?", a_en:"Yes", a_tr:"Evet"}, {q:"Was she killed in a car accident?", a_en:"No", a_tr:"Hayır"} ]
}];lessonData["11_HisayukiMachii.mp3"] = [{
    text: "11. Hisayuki Machii. Hisayuki Machii was a very powerful and influential figure in the Japanese underworld. He was an ethnic Korean living in Japan after World War II. He founded the Tosei-kai, a major Yakuza group in Tokyo. Machii was unique because he used his criminal power to build a massive legitimate business empire as well. He became a 'fixer' who helped the Japanese government and big companies solve problems. He was also a bridge between Japan and South Korea, helping with high-level politics and business deals. His group was involved in many activities, from construction to entertainment. Machii was a master of 'Soft Power' and was respected by both criminals and politicians. He was a very wealthy man who controlled the famous Ginza district in Tokyo. He is remembered as one of the most successful Yakuza bosses because he managed to move between the world of crime and the world of high-level business for many decades.",
    dict: { "influential": "etkili", "ethnic": "etnik", "unique": "eşsiz/benzersiz", "legitimate": "yasal/meşru", "fixer": "sorun çözücü", "bridge": "köprü", "construction": "inşaat", "entertainment": "eğlence", "respected": "saygı duyulan", "district": "bölge" },
    questions: [ {q:"Was he an influential figure in the Japanese underworld?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he build a legitimate business empire?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a bridge between Japan and South Korea?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he hated by politicians?", a_en:"No", a_tr:"Hayır"}, {q:"Did he control the Ginza district?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a master of Soft Power?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he only do illegal things?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["12_WhiteyBulger.mp3"] = [{
    text: "12. James Whitey Bulger. Whitey Bulger was a fearsome Irish-American mob boss who ruled the underworld of South Boston for many years. He was the leader of the 'Winter Hill Gang.' Bulger was a very violent man who was involved in murders, drug deals, and extortion. However, he had a dark secret: for many years, he was a secret informant for the FBI. He gave the FBI information about the Italian Mafia, and in exchange, the FBI protected him and allowed him to continue his own crimes. This allowed him to become the most powerful criminal in Boston. In 1994, when he found out the police were finally going to arrest him, he went into hiding. He was on the FBI's Most Wanted List for 16 years, right behind Osama bin Laden. He was finally caught in California in 2011 at the age of 81. He was sent to prison for life and was eventually killed by other prisoners in 2018. His story shows the corruption that can happen between police and criminals.",
    dict: { "fearsome": "korkutucu", "ruled": "yönetti", "extortion": "haraç/zorla para alma", "informant": "muhbir", "exchange": "karşılığında", "protected": "korudu", "allowed": "izin verdi", "hiding": "saklanma", "caught": "yakalandı", "corruption": "yolsuzluk" },
    questions: [ {q:"Was Whitey Bulger a fearsome mob boss?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a secret informant for the FBI?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the FBI protect him?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he go into hiding in 1994?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he caught when he was 20 years old?", a_en:"No", a_tr:"Hayır"}, {q:"Was he sent to prison for life?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he eventually killed by other prisoners?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["13_ElChapo.mp3"] = [{
    text: "13. Joaquin El Chapo Guzman. Joaquín Guzmán, known as 'El Chapo' because he is short, was the head of the Sinaloa Cartel in Mexico. He became the most powerful drug trafficker in the world after the death of Pablo Escobar. His cartel built a massive network of secret tunnels under the US-Mexico border to move drugs. El Chapo became a legend because he escaped from high-security prisons twice. Once, he escaped in a laundry basket, and the second time, his men dug a mile-long tunnel directly under his prison cell. He was very wealthy and appeared on the Forbes list of the world's billionaires. He was a very violent leader who was involved in a bloody war against other cartels and the Mexican government. Finally, in 2016, he was caught again and sent to the United States. He was sentenced to life in prison in a 'Supermax' facility where he can never escape again.",
    dict: { "short": "kısa", "trafficker": "kaçakçı/tüccar", "tunnels": "tüneller", "border": "sınır", "legend": "efsane", "escaped": "kaçtı", "laundry basket": "çamaşır sepeti", "dug": "kazdı", "billionaires": "milyarderler", "facility": "tesis" },
    questions: [ {q:"Is he called El Chapo because he is tall?", a_en:"No", a_tr:"Hayır"}, {q:"Did his cartel build secret tunnels under the border?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he escape from prison twice?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he escape in a laundry basket?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a very poor man?", a_en:"No", a_tr:"Hayır"}, {q:"Was he sent to the United States in 2016?", a_en:"Yes", a_tr:"Evet"}, {q:"Can he escape from the Supermax facility?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["14_JohnGotti.mp3"] = [{
    text: "14. John Gotti. John Gotti was the flamboyant and famous boss of the Gambino crime family in New York. He became the boss after he ordered the murder of the previous leader, Paul Castellano, in front of a steakhouse. Gotti loved the spotlight; he wore expensive silk suits and appeared on the covers of magazines. He was called 'The Dapper Don' because of his style and 'The Teflon Don' because the government failed to convict him in three different trials. He became a celebrity in New York, and many people liked him. However, his own underboss, Sammy 'The Bull' Gravano, eventually decided to talk to the FBI. With Gravano's help, the government finally proved Gotti was a murderer and a mob boss. In 1992, he was sent to prison for life. He died of cancer in prison in 2002. Gotti was the last of the 'celebrity' Mafia bosses who ruled with a public face.",
    dict: { "flamboyant": "gösterişli", "ordered": "emretti", "murder": "cinayet", "spotlight": "ilgi odağı", "silk suits": "ipek takım elbiseler", "convict": "mahkum etmek", "trials": "duruşmalar/mahkemeler", "celebrity": "ünlü", "underboss": "alt patron", "proved": "kanıtladı" },
    questions: [ {q:"Was John Gotti a famous boss?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he order the murder of Paul Castellano?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he hate the spotlight?", a_en:"No", a_tr:"Hayır"}, {q:"Did he wear expensive silk suits?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the government fail to convict him in three trials?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Sammy the Bull talk to the FBI?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Gotti die of cancer in prison?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["15_KhosrowTheKhan.mp3"] = [{
    text: "15. Khosrow The Khan. Khosrow, often called 'The Khan,' was a very mysterious and powerful figure in the world of international smuggling. He did not belong to a traditional Mafia family, but he managed a vast global network that moved illegal goods across continents. He was a master of logistics and used a fleet of ships and trucks to move everything from gold to dangerous weapons. He was known for being a 'shadow' figure who was very difficult for international police to track. He had connections with many different governments and criminal organizations. The Khan was a very wealthy man who lived a luxury life in different countries, always staying one step ahead of the law. He treated smuggling like a global shipping business and was one of the first to use modern technology to coordinate his crimes. His story is a famous example of how 'independent' criminals can become just as powerful as the traditional Mafia by using the systems of global trade.",
    dict: { "mysterious": "gizemli", "smuggling": "kaçakçılık", "vast": "devasa/geniş", "continents": "kıtalar", "logistics": "lojistik", "fleet": "filo", "shadow": "gölge", "track": "takip etmek", "independent": "bağımsız", "trade": "ticaret" },
    questions: [ {q:"Was Khosrow a very mysterious figure?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he belong to a traditional Mafia family?", a_en:"No", a_tr:"Hayır"}, {q:"Did he move illegal goods across continents?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he use a fleet of ships and trucks?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he easy for the police to track?", a_en:"No", a_tr:"Hayır"}, {q:"Did he use modern technology to coordinate his crimes?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a very wealthy man?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["16_MeyerLansky.mp3"] = [{
    text: "16. Meyer Lansky. Meyer Lansky was known as the 'Mob's Accountant.' He was a brilliant Jewish-American mobster who was the best friend and partner of Lucky Luciano. Lansky was a genius with numbers and money. He helped the Mafia build a massive gambling empire in Las Vegas, Cuba, and the Bahamas. He believed that the Mafia should be run like a corporation and focused on making money rather than fighting. He was a key advisor to 'The Commission' for many decades. Lansky was very quiet and avoided the spotlight; he lived in a simple house and looked like a normal businessman. Even though the FBI followed him for 50 years, they could never prove he was a major criminal. He tried to move to Israel to escape the US government, but he was forced to return. He died of old age in Miami in 1983. It is said that he had hundreds of millions of dollars hidden in secret bank accounts that were never found.",
    dict: { "accountant": "muhasebeci", "brilliant": "çok zeki/dahi", "partner": "ortak", "genius": "dahi", "corporation": "şirket/kurum", "advisor": "danışman", "avoided": "kaçındı", "prove": "kanıtlamak", "hidden": "gizli" },
    questions: [ {q:"Was Meyer Lansky known as the Mob's Accountant?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a genius with numbers and money?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he believe the Mafia should run like a corporation?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he love the spotlight and attention?", a_en:"No", a_tr:"Hayır"}, {q:"Could the FBI ever prove he was a major criminal?", a_en:"No", a_tr:"Hayır"}, {q:"Did he die of old age in Miami?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he have secret bank accounts?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["17_NickyBarnes.mp3"] = [{
    text: "17. Nicky Barnes. Leroy 'Nicky' Barnes was a massive drug kingpin in Harlem during the 1970s. He was the leader of a group called 'The Council,' which was a board of seven Black drug lords who organized the trade in the city. Barnes was known for his incredible wealth and his love of luxury cars and clothes. He became famous when he appeared on the cover of The New York Times Magazine with the title 'Mr. Untouchable.' This made President Jimmy Carter very angry, and he ordered the police to catch Barnes. Barnes was eventually arrested and sentenced to life in prison. While he was in jail, he discovered that his partners in 'The Council' were cheating him. He became very angry and decided to become an informant for the government. He gave the police enough information to arrest almost all of his former friends. He was eventually released from prison and lived the rest of his life under a new name in the witness protection program.",
    dict: { "kingpin": "elebaşı/baron", "organized": "organize etti", "wealth": "zenginlik", "cover": "kapak", "untouchable": "dokunulmaz", "angry": "kızgın", "sentenced": "mahkum edildi", "discovered": "keşfetti", "cheating": "kandırmak/aldatmak", "informant": "muhbir", "former": "eski", "witness protection": "tanık koruma" },
    questions: [ {q:"Was Nicky Barnes a major drug kingpin?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he love luxury cars and clothes?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he appear on the cover of a magazine?", a_en:"Yes", a_tr:"Evet"}, {q:"Was President Jimmy Carter happy about this?", a_en:"No", a_tr:"Hayır"}, {q:"Did Barnes discover his partners were cheating him?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he become an informant for the government?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he live his life under a new name later?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["18_PabloEscobar.mp3"] = [{
    text: "18. Pablo Escobar. Pablo Escobar was the head of the Medellín Cartel and the most famous drug lord in history. He became one of the richest men in the world by flooding the United States with cocaine. At the height of his power, he was making millions of dollars every day. He was a very violent man who used a rule called 'Plata o Plomo,' which means 'Silver or Lead'—you either take his money or you get shot. He was responsible for the deaths of thousands of people, including judges, police, and politicians. However, he was also popular with some poor people in Colombia because he built houses and soccer fields for them. He even built his own luxury prison called 'La Catedral' to avoid being sent to the US. Finally, after a long hunt by the Colombian police and the US, he was shot and killed on a rooftop in Medellín in 1993. His life remains a famous example of the extreme power and violence of the drug cartels.",
    dict: { "flooding": "sel gibi doldurma", "height": "zirve", "lead": "kurşun", "responsible": "sorumlu", "judges": "hakimler", "popular": "popüler", "avoid": "kaçınmak", "hunt": "av/arama", "rooftop": "çatı", "extreme": "aşırı" },
    questions: [ {q:"Was Pablo Escobar the head of the Medellín Cartel?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he make millions of dollars every day?", a_en:"Yes", a_tr:"Evet"}, {q:"Did 'Plata o Plomo' mean silver or lead?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he hated by all the poor people?", a_en:"No", a_tr:"Hayır"}, {q:"Did he build his own luxury prison?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he shot and killed on a rooftop?", a_en:"Yes", a_tr:"Evet"}, {q:"Is his life a famous example of cartel power?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["19_SemionMogilevich.mp3"] = [{
    text: "19. Semion Mogilevich. Semion Mogilevich is often called the 'Boss of Bosses' of the Russian Mafia. He is considered by the FBI to be one of the most dangerous and powerful criminals in the world today. He has a degree in economics and is a brilliant businessman who uses his mind to run a global criminal empire. His organization is involved in everything from energy companies to money laundering and arms trafficking. He is a very mysterious figure who lives in Moscow under the protection of his connections. He is known for being extremely clever and for using the international banking system to hide billions of dollars. Unlike the old-fashioned gangsters, Mogilevich operates in the world of high finance and international trade. He has managed to avoid arrest for decades and is on the FBI's Most Wanted List. He is a symbol of the modern, globalized criminal who is more powerful than many small countries.",
    dict: { "dangerous": "tehlikeli", "economics": "ekonomi", "laundering": "para aklama", "arms trafficking": "silah kaçakçılığı", "mysterious": "gizemli", "protection": "koruma", "banking system": "bankacılık sistemi", "billions": "milyarlar", "globalized": "küreselleşmiş" },
    questions: [ {q:"Is Semion Mogilevich called the Boss of Bosses?", a_en:"Yes", a_tr:"Evet"}, {q:"Does he have a degree in economics?", a_en:"Yes", a_tr:"Evet"}, {q:"Is his organization involved in money laundering?", a_en:"Yes", a_tr:"Evet"}, {q:"Is he a very mysterious figure?", a_en:"Yes", a_tr:"Evet"}, {q:"Does he use the international banking system to hide money?", a_en:"Yes", a_tr:"Evet"}, {q:"Has he managed to avoid arrest for decades?", a_en:"Yes", a_tr:"Evet"}, {q:"Is he on the FBI's Most Wanted List?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["20_StephanieStClair.mp3"] = [{
    text: "20. Stephanie St. Clair. Stephanie St. Clair, known as 'Queenie,' was a fierce and independent female gang leader in Harlem. She was born in the Caribbean and moved to New York, where she built a massive criminal business running the 'Numbers Game' (an illegal lottery). She was a very brave woman who refused to pay the Italian Mafia for protection. She fought against famous mobsters like Dutch Schultz and even placed advertisements in the newspapers to criticize the police for being corrupt. She was a hero to many people in Harlem because she stood up to the white gangs and protected her business. Queenie was known for her elegant style and her very tough personality. She eventually made a deal with Bumpy Johnson to help run her rackets. She survived the gang wars and retired as a wealthy woman. She is remembered as one of the few women who successfully ruled a major criminal empire in the middle of a very violent era.",
    dict: { "fierce": "şiddetli/çetin", "independent": "bağımsız", "female": "kadın", "lottery": "piyango", "brave": "cesur", "criticize": "eleştirmek", "corrupt": "yozlaşmış", "elegant": "zarif", "tough": "sert/dayanıklı", "retired": "emekli oldu", "era": "çağ/dönem" },
    questions: [ {q:"Was Stephanie St. Clair a female gang leader?", a_en:"Yes", a_tr:"Evet"}, {q:"Was she known as Queenie?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she pay the Italian Mafia for protection?", a_en:"No", a_tr:"Hayır"}, {q:"Did she criticize the police in newspapers?", a_en:"Yes", a_tr:"Evet"}, {q:"Was she a hero to many people in Harlem?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she make a deal with Bumpy Johnson?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she survive the wars and retire wealthy?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["21_VitoGenovese.mp3"] = [{
    text: "21. Vito Genovese. Vito Genovese was a powerful and very feared boss of the American Mafia. He was known for being extremely violent and for wanting to be the 'Boss of All Bosses.' In the 1930s, he fled to Italy to avoid a murder trial. While he was there, he became a close friend of the dictator Benito Mussolini and ran a large black-market business. After World War II, he was brought back to the US for trial, but the main witness was poisoned in his prison cell, so Genovese went free. He spent the next decade fighting to become the top boss of the New York families. He organized the famous 'Apalachin Meeting' in 1957, where bosses from all over the country met, but the police raided the meeting and arrested many of them. This was a huge disaster for the Mafia. Genovese was eventually sent to prison for drug trafficking, where he died in 1969. He is remembered as a boss whose greed and violence caused many problems for the Mafia.",
    dict: { "feared": "korkulan", "fled": "kaçtı", "trial": "duruşma/mahkeme", "dictator": "diktatör", "black-market": "karaborsa", "witness": "tanık", "poisoned": "zehirlendi", "raided": "baskın yaptı", "arrested": "tutukladı", "disaster": "felaket", "greed": "açgözlülük" },
    questions: [ {q:"Was Vito Genovese a feared boss?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he flee to Italy to avoid a trial?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he friends with the dictator Benito Mussolini?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the main witness poisoned in his cell?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the police raid the Apalachin Meeting?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the raid a huge success for the Mafia?", a_en:"No", a_tr:"Hayır"}, {q:"Did he die in prison?", a_en:"Yes", a_tr:"Evet"} ]
}];
